<footer class="site-footer relative bg-white overflow-hidden border-t border-brand-bordergray" style="height:469px">
  <div class="footer-background-art absolute inset-x-0 bottom-0 h-[360px]"><img src="assets/imgs/svg footer.svg" alt="" class="w-full h-full object-contain object-bottom"></div>
  <div class="relative h-full px-6 lg:px-[101px] pt-[62px]">
    <div class="flex flex-col lg:flex-row justify-between gap-10">
      <div class="max-w-[316px]">
        <div class="flex items-center gap-[10.54px] mb-6"><a href="index.php"><img src="assets/imgs/logo-sp.png" alt="Survey Pacific" class="h-[42.26px] object-contain"></a></div>
        <h3 class="text-[30px] font-bold leading-9 text-brand-textdark font-helvetica">People make markets.</h3>
        <p class="text-[14px] leading-[22.75px] text-[#656363] mt-2 max-w-[300px]">Independent research and data collection for better decisions.</p>
        <div class="flex gap-[16px] mt-[30px]"><img src="assets/imgs/instaicon.png" alt="Instagram" class="w-[24px] h-[24px] object-contain"><img src="assets/imgs/linkedin.png" alt="LinkedIn" class="w-[24px] h-[24px] object-contain"></div>
      </div>
      <div class="grid grid-cols-2 sm:grid-cols-4 gap-8">
        <div class="w-[171.6px]"><h4 class="text-[12px] font-bold uppercase tracking-[1.2px] text-[rgba(16,38,51,0.79)] font-helvetica">Research</h4><ul class="mt-5 space-y-2.5"><li><a href="market-research.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Market Research</a></li><li><a href="user-research.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">User Research</a></li><li><a href="social-research.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Social &amp; Public Research</a></li><li><a href="brand-consumer-research.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Brand &amp; Consumer Insights</a></li></ul></div>
        <div class="w-[171.6px]"><h4 class="text-[12px] font-bold uppercase tracking-[1.2px] text-[rgba(16,38,51,0.79)] font-helvetica">Data Collection</h4><ul class="mt-4 space-y-2"><li><a href="online-survey.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Online Surveys</a></li><li><a href="face-to-face-survey.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Face-to-Face Survey</a></li><li><a href="telephone-cati-survey.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Telephone/CATI Survey</a></li><li><a href="depth-interviews.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Depth Interviews</a></li><li><a href="focus-groups.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Focus Groups</a></li><li><a href="product-testing.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Product Testing</a></li><li><a href="mystery-shop.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Mystery Shop</a></li><li><a href="diary-studies.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Diary Studies</a></li><li><a href="multi-country-fieldwork.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Multi-Country Fieldwork</a></li></ul></div>
        <div class="w-[171.6px]"><h4 class="text-[12px] font-bold uppercase tracking-[1.2px] text-[rgba(16,38,51,0.79)] font-helvetica">Company</h4><ul class="mt-5 space-y-2.5"><li><a href="about-us.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">About Survey Pacific</a></li><li><a href="global-network.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Global Network</a></li><li><a href="leadership.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Leadership</a></li><li><a href="careers.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Careers</a></li><li><a href="#" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Research Ethics</a></li><li><a href="contact-us.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Contact</a></li></ul></div>
        <div class="w-[171.6px]"><h4 class="text-[12px] font-bold uppercase tracking-[1.2px] text-[rgba(16,38,51,0.79)] font-helvetica">Participants &amp; Partners</h4><ul class="mt-5 space-y-2.5"><li><a href="#" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Join WeSample</a></li><li><a href="become-supplier.php" class="text-[13px] text-[#1E354A] hover:text-brand-blue transition">Become a Supplier</a></li></ul></div>
      </div>
    </div>
    <button id="backToTop" class="fixed bottom-[30px] right-[30px] z-50 w-[52px] h-[52px] bg-brand-blue rounded-full shadow-[0_5.76px_5.76px_rgba(0,0,0,0.15)] flex items-center justify-center hover:bg-blue-700 transition opacity-0 invisible" aria-label="Back to top"><svg class="w-6 h-6 text-white transform rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 14l-7 7m0 0l-7-7m7 7V3"/></svg></button>
    <div class="absolute inset-x-6 lg:inset-x-[101px] bottom-[20px] flex flex-col sm:flex-row gap-4 justify-between items-start sm:items-center"><p class="text-[12px] text-white font-normal leading-4">&copy; 2026 Survey Pacific Private Limited. All rights reserved.</p><div class="flex flex-wrap gap-6"><a href="#" class="text-[12px] text-[#D4DAE0] hover:text-white transition">Privacy Policy</a><a href="#" class="text-[12px] text-[#D4DAE0] hover:text-white transition">Terms of Use</a><a href="#" class="text-[12px] text-[#D4DAE0] hover:text-white transition">Cookie Policy</a><a href="#" class="text-[12px] text-[#D4DAE0] hover:text-white transition">Sitemap</a></div></div>
  </div>
</footer>

<?php include __DIR__ . '/study-modal.php'; ?>
